
// This file has been generated by the GUI designer. Do not modify.
public partial class MainWindow
{
	private global::Gtk.VBox vbox8;
	private global::Gtk.Label Titulo;
	private global::Gtk.HBox hbox4;
	private global::Gtk.VBox vbox9;
	private global::Gtk.Button dado1;
	private global::Gtk.Button dado2;
	private global::Gtk.Button dado3;
	private global::Gtk.VBox vbox10;
	private global::Gtk.Label label1;
	private global::Gtk.Label label2;
	private global::Gtk.Label label3;
	private global::Gtk.HBox hbox5;
	private global::Gtk.Label label10;
	private global::Gtk.Label total;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox8 = new global::Gtk.VBox ();
		this.vbox8.Name = "vbox8";
		this.vbox8.Spacing = 6;
		// Container child vbox8.Gtk.Box+BoxChild
		this.Titulo = new global::Gtk.Label ();
		this.Titulo.Name = "Titulo";
		this.Titulo.LabelProp = global::Mono.Unix.Catalog.GetString ("Lanzar Dados");
		this.vbox8.Add (this.Titulo);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox8 [this.Titulo]));
		w1.Position = 0;
		w1.Expand = false;
		w1.Fill = false;
		// Container child vbox8.Gtk.Box+BoxChild
		this.hbox4 = new global::Gtk.HBox ();
		this.hbox4.Name = "hbox4";
		this.hbox4.Spacing = 6;
		// Container child hbox4.Gtk.Box+BoxChild
		this.vbox9 = new global::Gtk.VBox ();
		this.vbox9.Name = "vbox9";
		this.vbox9.Spacing = 6;
		// Container child vbox9.Gtk.Box+BoxChild
		this.dado1 = new global::Gtk.Button ();
		this.dado1.CanFocus = true;
		this.dado1.Name = "dado1";
		this.dado1.UseUnderline = true;
		this.dado1.Label = global::Mono.Unix.Catalog.GetString ("Dado 6");
		this.vbox9.Add (this.dado1);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox9 [this.dado1]));
		w2.Position = 0;
		w2.Expand = false;
		w2.Fill = false;
		// Container child vbox9.Gtk.Box+BoxChild
		this.dado2 = new global::Gtk.Button ();
		this.dado2.CanFocus = true;
		this.dado2.Name = "dado2";
		this.dado2.UseUnderline = true;
		this.dado2.Label = global::Mono.Unix.Catalog.GetString ("Dado 12");
		this.vbox9.Add (this.dado2);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox9 [this.dado2]));
		w3.Position = 1;
		w3.Expand = false;
		w3.Fill = false;
		// Container child vbox9.Gtk.Box+BoxChild
		this.dado3 = new global::Gtk.Button ();
		this.dado3.CanFocus = true;
		this.dado3.Name = "dado3";
		this.dado3.UseUnderline = true;
		this.dado3.Label = global::Mono.Unix.Catalog.GetString ("Dado 20");
		this.vbox9.Add (this.dado3);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox9 [this.dado3]));
		w4.Position = 2;
		w4.Expand = false;
		w4.Fill = false;
		this.hbox4.Add (this.vbox9);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.vbox9]));
		w5.Position = 0;
		w5.Expand = false;
		w5.Fill = false;
		// Container child hbox4.Gtk.Box+BoxChild
		this.vbox10 = new global::Gtk.VBox ();
		this.vbox10.Name = "vbox10";
		this.vbox10.Spacing = 6;
		// Container child vbox10.Gtk.Box+BoxChild
		this.label1 = new global::Gtk.Label ();
		this.label1.WidthRequest = 20;
		this.label1.HeightRequest = 30;
		this.label1.Name = "label1";
		this.vbox10.Add (this.label1);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox10 [this.label1]));
		w6.Position = 0;
		w6.Expand = false;
		w6.Fill = false;
		// Container child vbox10.Gtk.Box+BoxChild
		this.label2 = new global::Gtk.Label ();
		this.label2.WidthRequest = 20;
		this.label2.HeightRequest = 30;
		this.label2.Name = "label2";
		this.vbox10.Add (this.label2);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox10 [this.label2]));
		w7.Position = 1;
		w7.Expand = false;
		w7.Fill = false;
		// Container child vbox10.Gtk.Box+BoxChild
		this.label3 = new global::Gtk.Label ();
		this.label3.WidthRequest = 20;
		this.label3.HeightRequest = 30;
		this.label3.Name = "label3";
		this.vbox10.Add (this.label3);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox10 [this.label3]));
		w8.Position = 2;
		w8.Expand = false;
		w8.Fill = false;
		this.hbox4.Add (this.vbox10);
		global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.vbox10]));
		w9.Position = 1;
		w9.Expand = false;
		w9.Fill = false;
		// Container child hbox4.Gtk.Box+BoxChild
		this.hbox5 = new global::Gtk.HBox ();
		this.hbox5.Name = "hbox5";
		this.hbox5.Spacing = 6;
		// Container child hbox5.Gtk.Box+BoxChild
		this.label10 = new global::Gtk.Label ();
		this.label10.Name = "label10";
		this.label10.LabelProp = global::Mono.Unix.Catalog.GetString ("Total: ");
		this.hbox5.Add (this.label10);
		global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.label10]));
		w10.Position = 0;
		w10.Expand = false;
		w10.Fill = false;
		// Container child hbox5.Gtk.Box+BoxChild
		this.total = new global::Gtk.Label ();
		this.total.Name = "total";
		this.total.LabelProp = global::Mono.Unix.Catalog.GetString ("0");
		this.hbox5.Add (this.total);
		global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.total]));
		w11.Position = 1;
		w11.Expand = false;
		w11.Fill = false;
		this.hbox4.Add (this.hbox5);
		global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.hbox5]));
		w12.Position = 2;
		this.vbox8.Add (this.hbox4);
		global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.vbox8 [this.hbox4]));
		w13.Position = 1;
		w13.Expand = false;
		w13.Fill = false;
		this.Add (this.vbox8);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 400;
		this.DefaultHeight = 300;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.dado1.Clicked += new global::System.EventHandler (this.OnDado1Clicked);
		this.dado2.Clicked += new global::System.EventHandler (this.OnDado2Clicked);
		this.dado3.Clicked += new global::System.EventHandler (this.OnDado3Clicked);
	}
}
