
// This file has been generated by the GUI designer. Do not modify.
public partial class MainWindow
{
	private global::Gtk.VBox vbox1;
	private global::Gtk.Label Titulo;
	private global::Gtk.HBox hbox3;
	private global::Gtk.Button lanzar;
	private global::Gtk.VBox vbox7;
	private global::Gtk.Entry r1;
	private global::Gtk.Entry r2;
	private global::Gtk.Entry r3;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox ();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.Titulo = new global::Gtk.Label ();
		this.Titulo.Name = "Titulo";
		this.Titulo.LabelProp = global::Mono.Unix.Catalog.GetString ("Dados");
		this.Titulo.Justify = ((global::Gtk.Justification)(2));
		this.vbox1.Add (this.Titulo);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.Titulo]));
		w1.Position = 0;
		w1.Expand = false;
		w1.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox3 = new global::Gtk.HBox ();
		this.hbox3.Name = "hbox3";
		this.hbox3.Spacing = 6;
		// Container child hbox3.Gtk.Box+BoxChild
		this.lanzar = new global::Gtk.Button ();
		this.lanzar.CanFocus = true;
		this.lanzar.Name = "lanzar";
		this.lanzar.UseUnderline = true;
		this.lanzar.Label = global::Mono.Unix.Catalog.GetString ("Lanzar");
		this.hbox3.Add (this.lanzar);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.lanzar]));
		w2.Position = 0;
		w2.Expand = false;
		w2.Fill = false;
		// Container child hbox3.Gtk.Box+BoxChild
		this.vbox7 = new global::Gtk.VBox ();
		this.vbox7.Name = "vbox7";
		this.vbox7.Spacing = 6;
		// Container child vbox7.Gtk.Box+BoxChild
		this.r1 = new global::Gtk.Entry ();
		this.r1.CanFocus = true;
		this.r1.Name = "r1";
		this.r1.IsEditable = true;
		this.r1.InvisibleChar = '•';
		this.vbox7.Add (this.r1);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox7 [this.r1]));
		w3.Position = 0;
		w3.Expand = false;
		w3.Fill = false;
		// Container child vbox7.Gtk.Box+BoxChild
		this.r2 = new global::Gtk.Entry ();
		this.r2.CanFocus = true;
		this.r2.Name = "r2";
		this.r2.IsEditable = true;
		this.r2.InvisibleChar = '•';
		this.vbox7.Add (this.r2);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox7 [this.r2]));
		w4.Position = 1;
		w4.Expand = false;
		w4.Fill = false;
		// Container child vbox7.Gtk.Box+BoxChild
		this.r3 = new global::Gtk.Entry ();
		this.r3.CanFocus = true;
		this.r3.Name = "r3";
		this.r3.IsEditable = true;
		this.r3.InvisibleChar = '•';
		this.vbox7.Add (this.r3);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox7 [this.r3]));
		w5.Position = 2;
		w5.Expand = false;
		w5.Fill = false;
		this.hbox3.Add (this.vbox7);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.vbox7]));
		w6.Position = 1;
		this.vbox1.Add (this.hbox3);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox3]));
		w7.Position = 1;
		w7.Expand = false;
		w7.Fill = false;
		this.Add (this.vbox1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 579;
		this.DefaultHeight = 412;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.lanzar.Clicked += new global::System.EventHandler (this.OnLanzarClicked);
	}
}
